version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - 9432:5432
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080
